### PR TITLE
Update sync.rs - Allow use of tcp:// for DOCKER_HOST

### PR DESCRIPTION
**Pull request by arhue**

### CODE REVIEW

**Comment by arhue** [comment]
Realised this might be slightly better way of doing this:

```
    let docker_host_value = if !docker_socket.starts_with("tcp://") {
        format!("unix://{}", docker_socket)
    } else {
        docker_socket.clone()
    };
    env::set_var("DOCKER_HOST", docker_host_value);
```

Can make the change if needed.

**Comment by BigBoot** [comment]
Hi and thanks for your PR, I think it would be a better idea to move the format!  Inside the unwrap_or_else on line 491, then there's no need to hardcode the prefixes (of which there are more than tcp:// and unix:// btw.

**Comment by BigBoot** [comment]
fixed on master

**Comment by arhue** [comment]
@BigBoot Sorry somehow missed this. I tried out the code from master, works great and solved the issue. Thank you very much

**Pull request closed without merging**
